package smpl.syntax;

import smpl.semantics.Visitor;
import smpl.sys.SmplException;
import smpl.values.SmplValue;

/**
  Class ASTExpLit.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTExpLit extends ASTExp {
    SmplValue<?> val;
    
    public ASTExpLit(SmplValue<?> v) {
        val = v;
    }

    public ASTExpLit(Integer v) {
        val = SmplValue.make(v);
    }
    
    public ASTExpLit(Double v) {
        val = SmplValue.make(v);
    }

    public ASTExpLit(Boolean v) {
        val = SmplValue.make(v);
    }

    public SmplValue<?> getVal() {
        return val;
    }

  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws SmplException {
    return v.visitASTExpLit(this, state);
  }
}
