package smpl.syntax;

import smpl.semantics.Visitor;
import smpl.sys.SmplException;

/**
 * Class ASTProgram. Intermediate representation class autogenerated by
 * CS34Q semantic generator. Created on Sat Oct 12 03:13:16 2013
 */
public class ASTProgram extends ASTExp {

    ASTStmtSequence statements;

    public ASTProgram(ASTStmtSequence statements) {
        this.statements = statements;
    }

    /**
     *
     * @return The sequence of statements making up this program
     */
    public ASTStmtSequence getSeq() {
        return statements;
    }

    @Override
    public <S, T> T visit(Visitor<S, T> v, S state) throws SmplException {
        return v.visitASTProgram(this, state);
    }
}
