
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 04 21:14:09 GMT 2018
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 26;
  public static final int CHAR = 47;
  public static final int CONCAT = 38;
  public static final int PERIOD = 37;
  public static final int READINT = 15;
  public static final int CASE = 13;
  public static final int INTEGER = 44;
  public static final int LPAREN = 27;
  public static final int SEMI = 33;
  public static final int INT = 18;
  public static final int HEX = 49;
  public static final int PRINTLN = 10;
  public static final int MINUS = 22;
  public static final int BITNEG = 12;
  public static final int RPAREN = 28;
  public static final int EMPTY_LIST = 55;
  public static final int AND = 41;
  public static final int NOT = 40;
  public static final int OR = 42;
  public static final int COMMA = 34;
  public static final int LAZY = 4;
  public static final int CALL = 3;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int ASSIGN = 36;
  public static final int IF = 8;
  public static final int ALTCHAR = 52;
  public static final int EOF = 0;
  public static final int EQUAL = 39;
  public static final int TRUE = 53;
  public static final int error = 1;
  public static final int BITOR = 14;
  public static final int MUL = 23;
  public static final int LCURLY = 31;
  public static final int UNICHAR = 51;
  public static final int MOD = 25;
  public static final int RCURLY = 32;
  public static final int REAL = 45;
  public static final int COMPARE = 43;
  public static final int COLON = 35;
  public static final int BIN = 50;
  public static final int LBRACE = 29;
  public static final int ELSE = 17;
  public static final int VARIABLE = 46;
  public static final int READ = 11;
  public static final int WHILE = 19;
  public static final int LET = 5;
  public static final int THEN = 7;
  public static final int RBRACE = 30;
  public static final int BITAND = 9;
  public static final int STRING = 48;
  public static final int PROC = 2;
  public static final int DEF = 6;
  public static final int FALSE = 54;
  public static final int REDEFINE = 20;
  public static final int PRINT = 16;
}

